#!/bin/tcsh -f
# -f Fast start. do not read the  .cshrc  file

# $Id: runDBClient,v 1.2 2003-06-02 17:50:01 taylor Exp $

if (! -f runDBClient) then
  # needed for relative directory usage
  echo "current directory is not <root>/PlanWorks/test"
  exit
endif

# ensure that $JAVA_HOME is set properly
if (${?JAVA_HOME}) then
  rm -f config.jv
  # must be done in sh, since java is an sh script
  if ("$OSTYPE" == "darwin") then # MacOSX
    sh -c "$JAVA_HOME/Commands/java -version 2> config.jv"
  else
    sh -c "$JAVA_HOME/bin/java -version 2> config.jv"
  endif
  set java_version = `cat config.jv`
  # echo java_version $java_version
  set version_2 = `echo $java_version | awk -F\" '{print $2}'`
  # echo version_2 $version_2
  if ("$OSTYPE" == "darwin") then # MacOSX
    set jdk_gt_eq_1_4 = true
    # note the expr -- : --
    set match_test = `expr $version_2 : '.*1\.4\.*'`
#     if ( $match_test == 0 ) then
#       echo "$JAVA_HOME not jdk1.4.*"
#       # note the expr -- : --
#       set match_test = `expr $version_2 : '.*1\.3\.*'`
#       set jdk_gt_eq_1_4 = false
#     endif
  else # Linux & Solaris
    set jdk_gt_eq_1_4 = true
    # note the expr match -- --
    set match_test = `expr match $version_2 '.*1\.4\.*'`
  endif
  # echo match_test $match_test 
  if ( $match_test == 0 ) then
    echo "$JAVA_HOME not jdk1.4.*"
    exit 1
  endif
else
  echo "JAVA_HOME not set"
  exit 1
endif

set currentDir = `pwd`

cd ../java/lib/eXist
bin/client.sh -C conf-nolog.xml

cd $currentDir

